### ISSUE TITLE
Handle references to types from other schemas

### ISSUE THREAD

**Issue by prolativ** [VirtusLab/besom#117]
Values of `$ref` fields in schemas can refer to
1) predefined pulumi types (e.g. `pulumi.json#/Archive`)
2) local types defined in the current schema (starting with `#`, e.g. `#/types/kubernetes:rbac.authorization.k8s.io%2Fv1beta1:Subject`)
3) external types defined in other schemas (with a prefix before `#`, e.g `/aws/v5.35.0/schema.json#/types/aws:s3%2FBucketWebsite:BucketWebsite`)

Currently we handle only 1) & 2). We schould handle 3) as well.
If a schema refers to external types, that should make the provider SDK library jar have a dependency on another provider's library.

**Comment by pawelprazak** [comment]
addressed by #280 and #281
