### ISSUE TITLE
Properly handle references to resource types used as properties of of other resource/output types

### ISSUE THREAD

**Issue by prolativ** [VirtusLab/besom#125]
E.g. `"$ref": "/aws/v5.31.0/schema.json#/resources/aws:ec2%2FsecurityGroupRule:SecurityGroupRule"` in EKS.

Currently such references break derivation of codecs.
Java handles such references specially: they're not wrapped in `Outputs` as fields of Args classes.

**Comment by pawelprazak** [comment]
Related to #144 and #292
