### ISSUE TITLE
Make sure our templates compile

### ISSUE THREAD

**Issue by lbialy** [VirtusLab/besom#155]
The best thing to do here would be to have a separate build workflow for them given they only require pulumi and should work in a clean env without any packages published locally.

**Comment by pawelprazak** [comment]
Yes, also for the upcoming examples.

The question is do we want to trigger templates and examples compilation on every PR or nightly?

**Comment by lbialy** [comment]
Depends on what resources we have for GHA I guess. Could start with a
requirement that a PR can't be merged into develop without last commit
passing that workflow, mostly because it will be quite a long running job.

**Comment by pawelprazak** [comment]
I believe we already test compilation on both, templates and examples.

What is missing is automatic addition to the test target.
