### ISSUE TITLE
Integration tests should not have hardcoded versions of core lib

### ISSUE THREAD

**Issue by lbialy** [VirtusLab/besom#166]
Integration tests are currently using directives to declare dependencies, e.g.:
`//> using lib "org.virtuslab::besom-random:4.13.2-core.0.0.2-SNAPSHOT"`
in `integration-tests/src/test/resources/random-example/run.scala`

This should not be the case - these deps should be provided dynamically on each execution of the workflow to test current. This could be as easy as turning them into templates and running sed before `pulumi up`.

**Comment by pawelprazak** [comment]
This was done as part of `codegen` integration tests, and integration tests refactoring.

We can generalize it more in the future, but currently the version is taken from `version.txt`, so I think we can safely close this issue as done.
