### ISSUE TITLE
Codegen needs to not mangle urn or id fields

### ISSUE THREAD

**Issue by lbialy** [VirtusLab/besom#198]
Codegen currently creates the full list of fields for a struct before applying mangling to it and so it can yield a `urn_` and `id_` field names. This is incorrect, these fields should join the already mangled list. This is related to the ovh `urn` field fiasco but it's a general logic problem in codegen that needs fixing.

**Comment by lbialy** [comment]
In current codegen it is impossible for mangling to yield `urn_` or `id_` because they are not listed as protected names. This issue should only lead to codegen rejecting schemas where resources define fields called `urn` or `id`.

**Comment by pawelprazak** [comment]
Fixed by #322
