### ISSUE TITLE
gcp and dependency issues when included to pulumi libraries

### ISSUE THREAD

**Issue by renghen** [VirtusLab/besom#211]
hi, to all

been trying to use besom with gcp but to no avail.

I included the libraries 
//> using dep "com.pulumi:pulumi:0.9.7"
//> using dep "com.pulumi:gcp:6.67.0"
in the project.scala
which look like this after the fact

//> using scala "3.3.1"
//> using plugin "org.virtuslab::besom-compiler-plugin:0.1.0"
//> using dep "org.virtuslab::besom-core:0.1.0"
//> using dep "org.virtuslab::besom-aws:6.2.1-core.0.1.0"
//> using dep "com.pulumi:pulumi:0.9.7"
//> using dep "com.pulumi:gcp:6.67.0"

I go the following issues
[error] ./project.scala:3:16
    [error] Conflicting dependencies:
    [error] io.grpc:grpc-core:[1.45.0] or [1.54.1] wanted by
    [error]
    [error]   io.grpc:grpc-netty:1.45.0 wants [1.45.0]
    [error]   └─ org.virtuslab:besom-core_3:0.1.0
    [error]      └─ org.virtuslab:besom-aws_3:6.2.1-core.0.1.0
    [error]
    [error]   io.grpc:grpc-netty-shaded:1.54.1 wants [1.54.1]
    [error]   └─ com.pulumi:pulumi:0.9.7
    [error]      └─ com.pulumi:gcp:6.67.0
    [error]
    [error] //> using dep "org.virtuslab::besom-core:0.1.0"
    [error]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    [error] ./project.scala:4:16
    [error] Conflicting dependencies:
    [error] io.grpc:grpc-core:[1.45.0] or [1.54.1] wanted by
    [error]
    [error]   io.grpc:grpc-netty:1.45.0 wants [1.45.0]
    [error]   └─ org.virtuslab:besom-core_3:0.1.0
    [error]      └─ org.virtuslab:besom-aws_3:6.2.1-core.0.1.0
    [error]
    [error]   io.grpc:grpc-netty-shaded:1.54.1 wants [1.54.1]
    [error]   └─ com.pulumi:pulumi:0.9.7
    [error]      └─ com.pulumi:gcp:6.67.0
    [error]
    [error] //> using dep "org.virtuslab::besom-aws:6.2.1-core.0.1.0"
    [error]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    [error] ./project.scala:5:16
    [error] Conflicting dependencies:
    [error] io.grpc:grpc-core:[1.45.0] or [1.54.1] wanted by
    [error]
    [error]   io.grpc:grpc-netty:1.45.0 wants [1.45.0]
    [error]   └─ org.virtuslab:besom-core_3:0.1.0
    [error]      └─ org.virtuslab:besom-aws_3:6.2.1-core.0.1.0
    [error]
    [error]   io.grpc:grpc-netty-shaded:1.54.1 wants [1.54.1]
    [error]   └─ com.pulumi:pulumi:0.9.7
    [error]      └─ com.pulumi:gcp:6.67.0
    [error]
    [error] //> using dep "com.pulumi:pulumi:0.9.7"
    [error]                ^^^^^^^^^^^^^^^^^^^^^^^
    [error] ./project.scala:6:16
    [error] Conflicting dependencies:
    [error] io.grpc:grpc-core:[1.45.0] or [1.54.1] wanted by
    [error]
    [error]   io.grpc:grpc-netty:1.45.0 wants [1.45.0]
    [error]   └─ org.virtuslab:besom-core_3:0.1.0
    [error]      └─ org.virtuslab:besom-aws_3:6.2.1-core.0.1.0
    [error]
    [error]   io.grpc:grpc-netty-shaded:1.54.1 wants [1.54.1]
    [error]   └─ com.pulumi:pulumi:0.9.7
    [error]      └─ com.pulumi:gcp:6.67.0
    [error]
    [error] //> using dep "com.pulumi:gcp:6.67.0"
    [error]                ^^^^^^^^^^^^^^^^^^^^^

**Comment by lbialy** [comment]
You are trying to use pulumi-java *with* besom. Besom is not an extension of pulumi-java, it's a fully standalone SDK. Drop:
```
//> using dep "com.pulumi:pulumi:0.9.7"
//> using dep "com.pulumi:gcp:6.67.0"
```

and replace AWS with:
```
//> using dep "org.virtuslab::besom-gcp:6.66.0-core.0.1.0"
```

How did you arrive at the idea that you should use `com.pulumi:pulumi:0.9.7` alongside besom? Was something in the docs unclear?

**Comment by renghen** [comment]
I tried looking for gcp in the docs, did not see it; and also looked into maven repo for besom, there a lot of packages there, I must have miss it.

I will try it right away and if it everything goes right I will close the issue.

**Comment by lbialy** [comment]
True, we don't have docs for packages yet. We'll sort it out soon. Feel free to ask questions if you get stuck again!

**Comment by pawelprazak** [comment]
Thank you for your report, I'll add a warning in the docs to not confuse java imports with besom by accident.

Please let us know if you were able to solve the problem and can we close this issue, or do you need more assistance?

**Comment by renghen** [comment]
it works, so I think we can close that
