### ISSUE TITLE
Weird behaviors when using secrets

### ISSUE THREAD

**Issue by lbialy** [VirtusLab/besom#276]
Secrets and secret propagation seems broken. Secret values don't get propagated to destination inputs. When interleaved with resource constructors secret Outputs cause deletions of resources (apparently resources do not get registered when invoked in a for-comp *after* a secret). The behaviour is consistent with empty Outputs that should only be used in dry runs so my suspicion is that Config module has a broken secret handling and returns empty outputs (instead of failed outputs for missing properties). Given how severe and hard to understand issues Output.empty creates I think we should rethink usage of the empty channel everywhere and limit it *strictly* to dry run property outputs because the Optionesque short-circuiting behavior is *very* confusing when used with Output.

Scope of this task:
* [ ] fix resolution of secrets from pulumi configuration
* [x] make config.get family return Output[Option[A]] instead of Output.empty
* [x] make config.require family return Output[A] or Output.fail

Some part of this is duplicated with 
* https://github.com/VirtusLab/besom/issues/204
* https://github.com/VirtusLab/besom/issues/205

**Comment by lbialy** [comment]
need to re-check after #287

**Comment by pawelprazak** [comment]
further improvements and unit and integration tests for secrets in #300
