### ISSUE TITLE
Scala Language Plugin for Pulumi should support all the executors that Java Language Plugin does

### ISSUE THREAD

**Issue by dubinsky** [VirtusLab/besom#303]
[Getting started](https://virtuslab.github.io/besom/docs/getting_started/) creates an impression that Scala CLI and Scala Language Plugin are required to use Besom. In fact, if the project uses one of the execution methods supported by the Pulumi Java Language Plugin (Gradle, Maven, JAR, JBang or SBT), Besom SDK can be used with `runtime: java` in `Pulumi.yaml`, just as Pulumi Java SDK can be used from Scala code that way. Indeed, if the project uses Gradle, Maven or JBang, Scala Language Plugin must **not** be used: while retaining support for JAR and SBT execution, it drops support for Gradle etc. in favour of Scala CLI. Scala Language Plugin seems to be required only if the project uses Scala CLI, and although this setup is recommended, I think the ability to use Besom with - say - Gradle should be at least mentioned ;)

**Comment by lbialy** [comment]
That is definitely true (in fact, before we've had language plugin we used
runtime: java). I see no reason not to document that and I didn't include
that fact in the first draft of docs only because I strived for a lean,
uncluttered and frictionless experience (as all DX should be!). I think we
can add sections regarding the use of other build tools available on the
platform. In fact, we should also support mill on Scala language plugin's
side if we don't do it yet.

**Comment by dubinsky** [comment]
@lbialy one way to remove _some_ friction is to copy from the Java language plugin to the Scala one not just the JAR and SBT executors but all of them (Gradle, Maven and JBang too); this way, by switching from the Java runtime to the Scala one one would _gain_ the ability to use Scala CLI - but would not _lose_ the ability to use - say - Gradle...

**Comment by dubinsky** [comment]
I am not sure what the Scala language plugin does, but I suspect that it provides more than just the executors. I can easily see how Besom might require the use of the Scala language plugin, and I am more than willing to switch to `runtime: scala` - as long as I do not lose the ability to use the build tool of my choosing that I can use now with `runtime: java`.

**Comment by lbialy** [comment]
Yeah, so the long game plan for language plugin is to support way more
features as planned by Pulumi, programmatic code generation on demand on
user's machine for starters. Current impl is just the same go app as
pulumi-java with changes so we could backport gradle etc very easily I
think. In the long run we want to rewrite it to Scala and compile with
native-image.

**Comment by dubinsky** [comment]
> plan for language plugin is to support way more
features

Cool!

> we could backport gradle etc very easily

From what I see, JAR and SBT support were just copied, so it's just more copying ;)
Ability to switch to `runtime: scala` without breaking Gradle is going to greatly improve DX ;)

**Comment by pawelprazak** [comment]
As for something immediately actionable, we probably should document that Java SDK and Besom are completely separate and can interact in unpredictable and "interesting" ways when used together.

**Comment by dubinsky** [comment]
@pawelprazak 
I understand that to continue to be able to use Besom I need to use `runtime: scala`, and I am happy - eager even! - to do it.
I also understand that when the Automation API becomes available, build-tool integration using it will become possible, and I am happy to look at the possibility of developing a Gradle plugin for such integration.

I do not quite understand the impact of this statement:

>  I've always thought the Pulumi way of doing language plugins is fundamentally incompatible with the "JVM-way", and the dependency should be IMO reversed.

Does this mean that at some point the ability to use Besom via the `pulumi` CLI delegating to the Besom's Scala Language Plugin is going to get removed completely? 

Before all of the above transpires, what is the way for me _right now_ to use Besom properly, with the Scala Language Plugin, if I am using Gradle as a build tool and the language plugin does not (and will not) support it? Should I point to my executable JAR in Pulumi.yaml's `runtime.option.binary` or is there a better way? Or am I out of luck and not a part of the target audience of the early adopters? ;)

Thanks!

**Comment by pawelprazak** [comment]
I'm sorry about my confusing remarks, I was just thinking out loud. There are no specific decisions made yet regarding language plugin, other than that **we'd like to find a way to give the community the best support for build tools possible**, and the exact shape of it, I hope, will be made clear by user feedback, like yours :)

This is a very good point you are making, about early adoption, and I see no reason no to port Java lang host Gradle support, @lbialy WDYT?

**Comment by dubinsky** [comment]
Will this be in the next release? ;)

**Comment by lbialy** [comment]
Ok, I'll take a look at this. I think we can include this in the upcoming
0.2.0.

**Comment by pawelprazak** [comment]
Reopening until release

**Comment by lbialy** [comment]
Release of 0.2.0 which brings support for Maven and Gradle is underway. Closing the issue.

**Comment by kryptt** [comment]
when setting a custom assembly jar (to use `mill` to compile the project) I get the following error: 

```
Diagnostics:
  pulumi:pulumi:Stack (bi-services-main):
    Error: An unexpected error occurred while trying to open file out/infra/assembly.dest/out.jar

    error: an unhandled error occurred: '/home/rhansen/.jabba/jdk/openjdk@1.17.0/bin/java /home/rhansen/.jabba/jdk/openjdk@1.17.0/bin/java -jar out/infra/assembly.dest/out.jar' exited with non-zero exit code: 1

```

It seems like: 
  a) the java executable is repeated (doubled) 
  b)  the path to the is relative to wherever its running from; I am expecting the project root, but, not sure....
