### ISSUE TITLE
Consider adding macro-driven Encoder that uses JsonFormat from scope

### ISSUE THREAD

**Issue by pawelprazak** [VirtusLab/besom#305]
When I try to export an arbitrary case class I get:
```
[error] Encoder[besom.internal.Output[Foo]] is missing
    [error]       foo = foo
    [error]             ^^^
```

Theoretically it should be possible to create a macro-based mechanism to automatically create `Encoder` for `Output[Foo]` if there is a `JsonFormat[A]`.

The implementation stops being trivial when we have nested Outputs.

Current workaround is to manually serialize, e.g.:
```scala
  import spray.json.DefaultJsonProtocol._
  import spray.json.JsonFormat
  case class Foo(name: String, age: Int)
  object Foo:
    given JsonFormat[Foo] = jsonFormat2(Foo.apply)

  val foo = config.requireObject[Foo]("foo")

  Output(
    exports(
      foo = foo.map(summon[JsonFormat[Foo]].write(_))
    )
  )
```

**Comment by lbialy** [comment]
won't this just do the work? sorry, not typechecked, my besom setup is still kill.

```
given jsonCaseClassEnc[A: JsonFormat](using ctx: Context, stringOutputEnc: Encoder[Output[String]]): Encoder[Output[A]] = 
  new Encoder[Output[A]]:
    def encode(outputA: Output[A]): Result[(Set[Resource], Value)] = 
      stringOutputEnc.encode(outputA.map(a => summon[JsonFormat[A]].write(a)))
```

**Comment by lbialy** [comment]
This actually calls for another issue @pawelprazak - if this error:
```
[error] Encoder[besom.internal.Output[Foo]] is missing
[error]       foo = foo
[error]  
``` 
is something a user can encounter when working with usual exports *we have to* have an @implicitNotFound on Encoder with a good message that would explain which primitive types are supported and what to do to support structural exports.

**Comment by lbialy** [comment]
can we close it now?

**Comment by lbialy** [comment]
This is actually actively harmful, we should not serialize anything using JSON in exports. Proper solution is `derives Encoder` on the case class used for export and it works without any issues and handles secrets properly too.
