### ISSUE TITLE
Address missing invoke and call APIs

### ISSUE THREAD

**Issue by lbialy** [VirtusLab/besom#31]
The 'invoke' and 'call' APIs are currently missing. It's also worth noting that 'call' isn't actually used in AWS.

**Comment by pawelprazak** [comment]
Make sure, invoke accepts Outputs:
https://www.pulumi.com/blog/functions-accept-outputs/

**Comment by pawelprazak** [comment]
Context for `call` https://github.com/pulumi/pulumi/issues/7072
