### ISSUE TITLE
Tutorial results in "BadRequestException: CloudWatch Logs role ARN must be set"

### ISSUE THREAD

**Issue by MartinHH** [VirtusLab/besom#347]
Hello there! I was just rather naively working though the [tutorial](https://virtuslab.github.io/besom/docs/tutorial)  and was a bit confused by this (which might be due to me being a total newbie regarding aws):

### Steps to reproduce:

1.  Follow the steps described in the [introduction](https://virtuslab.github.io/besom/docs/tutorial#introduction) section of the [tutorial](https://virtuslab.github.io/besom/docs/tutorial) 
2. Checkout the  `complete` branch from https://github.com/VirtusLab/besom-tutorial
3. run `pulumi up`

### Expected result

`pulumi up` succeeds without any errors.

### Actual result

`pulumi up` shows the following error:

```
 +   └─ aws:apigateway:MethodSettings   apiStageSettings                                   **creating failed**           1 error

Diagnostics:
  pulumi:pulumi:Stack (besom-tutorial-dev):
    error: update failed

  aws:apigateway:MethodSettings (apiStageSettings):
    error: 1 error occurred:
    	* updating API Gateway Stage failed: BadRequestException: CloudWatch Logs role ARN must be set in account settings to enable logging
```

### Workaround

Outcomment the `loggingLevel = "ERROR"` line of the `apiStageSettings`:
```scala
  val apiStageSettings = apigateway.MethodSettings(
    "apiStageSettings",
    apigateway.MethodSettingsArgs(
      restApi = api.id,
      stageName = apiStage.stageName,
      methodPath = "*/*",
      settings = MethodSettingsSettingsArgs(
        metricsEnabled = true,
//        loggingLevel = "ERROR"
      )
    )
  )
```

This is probably not a big deal - judging from my search results, the underlying problem seems to be very common (and well-explained), but I guess the tutorial would be even more inviting if it provided a solution or at least some obvious hints for solving this properly.
(Sorry in advance if this turns out to be a case of "I just did not read the tutorial properly".)

**Comment by lbialy** [comment]
Hey, sorry for this experience! It's possible that something has drifted, cloud APIs are a moving target. You say that this happens on clean `complete` branch, right? Let me see if I can replicate and get back to you.

**Comment by lbialy** [comment]
Hi again:
![im-back](https://github.com/VirtusLab/besom/assets/8607442/f8272d17-c907-4513-accb-15a55b9e8653)

I've run the complete branch of the tutorial and:
```
λ pulumi up                                                                                                                                                                                                                   0 (0.006s) < 13:09:01
Please choose a stack, or create a new one: dev
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):
Enter your passphrase to unlock config/secrets
Previewing update (dev):
     Type                               Name                                               Plan
 +   pulumi:pulumi:Stack                besom-tutorial-dev                                 create
 +   ├─ aws:s3:Bucket                   pulumi-catpost-cat-pics                            create
 +   ├─ aws:s3:BucketPublicAccessBlock  pulumi-catpost-cat-pics-ed9be9b-publicaccessblock  create
 +   ├─ aws:s3:BucketPolicy             pulumi-catpost-cat-pics-ed9be9b-access-policy      create
 +   ├─ aws:dynamodb:Table              pulumi-catpost-table                               create
 +   ├─ aws:iam:Role                    lambda-role                                        create
 +   ├─ aws:lambda:Function             pulumi-render-feed                                 create
 +   ├─ aws:cloudwatch:LogGroup         /aws/lambda/pulumi-render-feed-50ca0e0             create
 +   ├─ aws:lambda:Function             pulumi-add-post                                    create
 +   ├─ aws:cloudwatch:LogGroup         /aws/lambda/pulumi-add-post-debccb0                create
 +   ├─ aws:apigateway:RestApi          api                                                create
 +   ├─ aws:lambda:Permission           feedLambdaPermission                               create
 +   ├─ aws:lambda:Permission           addLambdaPermission                                create
 +   ├─ aws:apigateway:Method           feedMethod                                         create
 +   ├─ aws:apigateway:Resource         addResource                                        create
 +   ├─ aws:apigateway:Method           addMethod                                          create
 +   ├─ aws:apigateway:Integration      feedIntegration                                    create
 +   ├─ aws:apigateway:Integration      addIntegration                                     create
 +   ├─ aws:apigateway:Deployment       apiDeployment                                      create
 +   ├─ aws:apigateway:Stage            apiStage                                           create
 +   └─ aws:apigateway:MethodSettings   apiStageSettings                                   create

Outputs:
    endpointURL: output<string>
    feedBucket : "pulumi-catpost-cat-pics-ed9be9b"

Resources:
    + 21 to create

Do you want to perform this update? yes
Updating (dev):
     Type                               Name                                               Status
 +   pulumi:pulumi:Stack                besom-tutorial-dev                                 created (34s)
 +   ├─ aws:s3:Bucket                   pulumi-catpost-cat-pics                            created (1s)
 +   ├─ aws:s3:BucketPublicAccessBlock  pulumi-catpost-cat-pics-a37fa4c-publicaccessblock  created (0.32s)
 +   ├─ aws:s3:BucketPolicy             pulumi-catpost-cat-pics-a37fa4c-access-policy      created (0.30s)
 +   ├─ aws:dynamodb:Table              pulumi-catpost-table                               created (6s)
 +   ├─ aws:iam:Role                    lambda-role                                        created (1s)
 +   ├─ aws:lambda:Function             pulumi-render-feed                                 created (12s)
 +   ├─ aws:cloudwatch:LogGroup         /aws/lambda/pulumi-render-feed-a582d9c             created (0.37s)
 +   ├─ aws:lambda:Function             pulumi-add-post                                    created (8s)
 +   ├─ aws:cloudwatch:LogGroup         /aws/lambda/pulumi-add-post-a13bedd                created (0.36s)
 +   ├─ aws:apigateway:RestApi          api                                                created (1s)
 +   ├─ aws:lambda:Permission           feedLambdaPermission                               created (0.28s)
 +   ├─ aws:lambda:Permission           addLambdaPermission                                created (0.27s)
 +   ├─ aws:apigateway:Method           feedMethod                                         created (0.06s)
 +   ├─ aws:apigateway:Resource         addResource                                        created (0.15s)
 +   ├─ aws:apigateway:Method           addMethod                                          created (0.08s)
 +   ├─ aws:apigateway:Integration      feedIntegration                                    created (0.14s)
 +   ├─ aws:apigateway:Integration      addIntegration                                     created (0.12s)
 +   ├─ aws:apigateway:Deployment       apiDeployment                                      created (0.28s)
 +   ├─ aws:apigateway:Stage            apiStage                                           created (0.30s)
 +   └─ aws:apigateway:MethodSettings   apiStageSettings                                   created (0.27s)

Outputs:
    endpointURL: "https://wkc2scy0z3.execute-api.eu-central-1.amazonaws.com/default"
    feedBucket : "pulumi-catpost-cat-pics-a37fa4c"

Resources:
    + 21 created

Duration: 37s
```

It works and I posted my favourite dog meme because I'm contrarian:
![Screenshot 2024-01-25 at 13 18 02](https://github.com/VirtusLab/besom/assets/8607442/e419d67e-3965-434c-8730-0f9b361b58ec)

What I have to ask in this case is - what permissions does your IAM account have (the one you're using access key for)? Tutorial introduction mentions that it's strongly advised to run with Administrator level account to avoid things like this:


**CAUTION**
It's strongly recommended that you use an IAM account with AdministratorAccess permissions as it guarantees that you won't encounter issues related to missing permissions. Additionally, it's also recommended to set your [default region](https://docs.aws.amazon.com/awsconsolehelpdocs/latest/gsg/select-region.html) in AWS Console.

If it's impossible for you maybe we can navigate around it but I will need to know what permissions you currently have so that we can add missing ones (probably cloudwatch related looking at the errror).

**Comment by pawelprazak** [comment]
Hi @MartinHH thank you for letting us know about your experience with the besom tutorial.

AFAIK this a known AWS error message, by default, API Gateway does not have the required permission to write logs to CloudWatch logs.

In terms of proper solution, I'd try to add proper IAM settings. Unfortunately this is far from straightforward.
Here is a starting point un upstream Pulumi: https://www.pulumi.com/registry/packages/aws/api-docs/apigateway/account/#example-usage

**Comment by pawelprazak** [comment]
I've just realized the example I gave uses functions, and those require the upcoming `0.2.0` version 😅

**Comment by lbialy** [comment]
Maybe we should try running it from a clean AWS account? Who knows what weird mutable state lurks in the depths of their databases.

**Comment by MartinHH** [comment]
> What I have to ask in this case is - what permissions does your IAM account have (the one you're using access key for)? 

The IAM account has AdministratorAccess. More precisely: I'm using an IAM account that is assigned to a group which has the AdministratorAccess policy attached to it.

(I'm running this from a brand new, clean aws account. That user and that group are the only user/group I created on it (besides the root user) and attaching AdministratorAccess to that group was the only assignment of access rights that I did.)

**Comment by lbialy** [comment]
Ok, so @pawelprazak must be right and I have set something in console while working on tutorial and forgot about it. I'm so sorry, I'll try with a blank slate AWS account in a moment. Thanks for reporting this, it means a lot :)

**Comment by pawelprazak** [comment]
requires #331

**Comment by pawelprazak** [comment]
I have repro on the same account I've tested the tutorial, so something must have changed in AWS API internals I guess:
```
aws:apigateway:MethodSettings (apiStageSettings):
    error: 1 error occurred:
    	* updating API Gateway Stage failed: BadRequestException: CloudWatch Logs role ARN must be set in account settings to enable logging
```

**Comment by pawelprazak** [comment]
I've made some changes and this PR solves the issue on the test account. Please let me know if it helps :)

https://github.com/VirtusLab/besom-tutorial/pull/3

**Comment by MartinHH** [comment]
> I've made some changes and this PR solves the issue on the test account. Please let me know if it helps :)
> 
> [VirtusLab/besom-tutorial#3](https://github.com/VirtusLab/besom-tutorial/pull/3)

Thanks. That solves the issue for me.

Meanwhile, I was also able to translate the solution suggested by pulumi's bot to besom and that works for me as well: https://github.com/MartinHH/besom-tutorial/commit/616f470bf30b4e0444a6d67d4a2ec75d3af54b2b

Both solutions are very similar, but: the bot's solution uses a `PolicyAttachment` where yours uses a `Policy`.

**Comment by lbialy** [comment]
There's also third solution using PolicyDocuments that @pawelprazak came up before that's even more complex. Aws APIs never make stuff easy, hopefully we can get remote components done soon and use awsx. By the way, we don't have versioned docs yet and we've merged updated docs including new Stack syntax, sorry for the mess, if it bothers you we can revert docs to the 0.1.0 tag version.

**Comment by pawelprazak** [comment]
@MartinHH great to hear you were successful in solving the issue 😃 

We've updated the tutorial and the tutorial repo.

Once we close #331 we'll be able to use the `getPolicyDocument` provider helper functions to make the examples cleaner, but functionally it's the same mechanism.

Please let us know if we can close the issue.

**Comment by MartinHH** [comment]
Again: thanks alot!

> Please let us know if we can close the issue.

Now that you're asking, I re-read the tutorial and noticed that [Addendum B](https://virtuslab.github.io/besom/docs/tutorial/#addendum-b---final-stack-block) is not updated yet.

Nevertheless: feel free to close this issue at your discretion.

**Comment by pawelprazak** [comment]
Thank you for the proof reading, I've missed a spot 😅 

Good luck!
