### ISSUE TITLE
Exception upon traverse

### ISSUE THREAD

**Issue by jchapuis** [VirtusLab/besom#430]
When running the [example](https://github.com/VirtusLab/besom/blob/3cba8863f80f0ab81af245f19dc89423187ec868/examples/aws-s3-folder/Main.scala#L64C14-L64C45 
) , prior removal of type information in the `val uploads = ` declaration leads to a runtime exception  

```
class scala.collection.immutable.$colon$colon cannot be cast to class scala.collection.View
[error] 	at scala.collection.BuildFrom$$anon$8.newBuilder(BuildFrom.scala:85)
[error] 	at besom.internal.Output$.sequence$$anonfun$1$$anonfun$1(Output.scala:123)
```

**Comment by pawelprazak** [comment]
Thank you for finding this, I was able to reproduce. As you've said, removing the explicit type from `val uploads` leads to compiler type inference confusion. Notable factor is the `toList` method is being called on a Java array.
We need to further investigate.

**Comment by lbialy** [comment]
Wow, this is actually a mind blowing issue in the compiler itself. This is, in my humble opinion, an exports-related bug. I have replicated this on this repro repo:
https://github.com/lbialy/besom-issue-430

**Comment by lbialy** [comment]
Reported to scala/scala3: https://github.com/scala/scala3/issues/20079
