### ISSUE TITLE
Add `@implicitNotFound` for `Result.ToFuture` with more helpful message

### ISSUE THREAD

**Issue by pawelprazak** [VirtusLab/besom#434]
The default compiler error can be quite puzzling without the knowledge about the implementation details, e.g.:

![image](https://github.com/VirtusLab/besom/assets/48874/acecc765-2694-4361-acdd-2bd716e94e01)

 in this case the compiler expected an `Output[B]` but got an `Option[Output[B]]`

**Comment by lbialy** [comment]
done via #443
