### ISSUE TITLE
Rewrite exports to traits-based solution from Scala 2

### ISSUE THREAD

**Issue by lbialy** [VirtusLab/besom#436]
Given our issues with exports feature of Scala 3:
* https://github.com/scala/scala3/issues/17930 - our component API requires passing ComponentResourceOptions() explicitly because `def component` is an exported function 
* our #430 happens because https://github.com/scala/scala3/issues/20079 - our sequence and traverse are exported implicit classes and it seems compiler loses type precision on them in some very weird way

we will probably be forced to revert to a scala 2 like way of composing our stuff without relying on `export` keyword until fixes are in. This means that stuff will have to go into traits that can be composed into package objects that user imports from. Key objective here is for this change to be completely source-compatible for any user code so:

NO CHANGES TO ANY EXAMPLES OR INTEGRATION TESTS ARE ALLOWED AT ALL.

**Comment by pawelprazak** [comment]
Makes sense, and as a small added benefit, IntelliJ will work better without the `export`, since it's not supported yet.

**Comment by lbialy** [comment]
WONTIMPLEMENT, we found a way to overcome export issues. Big thanks to @prolativ!
