### ISSUE TITLE
Add parSequence and parTraverse combinators to Result and Output

### ISSUE THREAD

**Issue by lbialy** [VirtusLab/besom#438]
Current implementation of sequence/traverse functions is sequential which can very easily lead to accidental serialisation of operations. Given that resource constructors can be painfully slow in infra it should be possible for the user to decide whether their side effects have to be executed in given order or in parallel. We *could* just make `sequence` and `traverse` parallel by default (I think that's how `Output.allOf` works in `pulumi-java` and `All`/`Output.all` combinators in [other](https://github.com/pulumi/pulumi/blob/c81c23635430716f3a65eb5ac75bc59048fd896a/sdk/nodejs/output.ts#L500-L507) SDKs  work given that **all** of them are strict!) but that could be misleading, surprising and not really helpful for people used to working with lazy monads in Scala.

**Comment by pawelprazak** [comment]
Sounds good. For the record, you are right, Java uses 
[CompletableFuture.allOf](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html#allOf-java.util.concurrent.CompletableFuture...-)
like [this](https://github.com/pulumi/pulumi-java/blob/5845cd879877fae8369de7ff0009c839d1a788e2/sdk/java/pulumi/src/main/java/com/pulumi/core/internal/CompletableFutures.java#L30)
```
public static <T> CompletableFuture<List<T>> allOf(Collection<CompletableFuture<T>> futures) {
        return CompletableFuture
                .allOf(futures.toArray(new CompletableFuture[futures.size()]))
                .thenApply(unused -> futures.stream()
                        .filter(ignoreNullValues())
                        .map(CompletableFuture::join) // join() is not blocking here, by the time this function is called, the future is guaranteed to be complete
                        .collect(Collectors.toList())
                );
    }
```

This will wait for all of the futures without any ordering. So it can be parallel in theory.

**Comment by lbialy** [comment]
In java it *is* parallel by default because CompletableFuture is not lazy :)

Implemented and done.
