### ISSUE TITLE
Understand `ResourceOptions.replaceOnChanges`

### ISSUE THREAD

**Issue by lbialy** [VirtusLab/besom#59]
Figure out what `ResourceOptions.replaceOnChanges` is and how it should be handled. Consider whether it should be strongly typed.

**Comment by pawelprazak** [comment]
According to [Pulumi docs](https://www.pulumi.com/docs/concepts/options/replaceonchanges/):

> [...] used to indicate that changes to certain properties on a resource should **force a replacement of the resource instead of an in-place update**. 
> Typically users rely on the resource provider to make this decision based on whether the input property is one that the provider knows how to update in place, or if not, requires a replacement to modify. 
> However, there are cases where users want to replace a resource on a change to an input property even if the resource provider itself doesn’t believe it has to replace the resource.

**Comment by pawelprazak** [comment]
NOTE: this functionality does the opposite of [`ignoreChanges`](https://www.pulumi.com/docs/concepts/options/ignorechanges/)

**Comment by pawelprazak** [comment]
review in context of #355

**Comment by lbialy** [comment]
implemented
